### ISSUE TITLE
General settings tab don't work and configuration of lat and lon of the map

### ISSUE THREAD

**Issue by JavierGallego** [madewithpepper/store-finder-pro#1]
Hi team!, thanks for this fantastic software but I have problems with the script I follow the installation instructions but I don't know when every time I click on general settings tab the screen show:

Whoops, looks like something went wrong....

and other question if is possible configure the default long and lat of the map¿? and where I can make the change?

Waiting for your soon reply...

**Comment by skokhuis** [comment]
Set debug to true in `/app/config/app.php` to see the actual error. Or `/app/config/production/app.php` if you override it there.

I can't think of a quick way to use lat/long, but the default location can be set in `/app/views/map/main.blade.php`. At line 40 you can add an address like this:

```php
$q = Request::get('q', 'The address you want to geocode');
```

**Comment by JavierGallego** [comment]
Hi team! fixed!, was a misconfiguration on the mail.

**Comment by skokhuis** [comment]
Great, thanks for following up!

**Comment by JavierGallego** [comment]
Is fantastic your script, is possible change the language of all the system?, because I can translate into spanish.

**Comment by JavierGallego** [comment]
I have other question where I can put a default zoom?

**Comment by skokhuis** [comment]
Check the main.blade.php for all these configs. And readme.html for
language.

Sem Kokhuis

*Made with Pepper*
madewithpepper.com

Our terms and services apply to our products and services;
madewithpepper.com/legal.

2016-01-12 14:06 GMT+01:00 Javier Gallego <notifications@github.com>:

**Comment by JavierGallego** [comment]
Great!, thanks again.
