### ISSUE TITLE
Info window on map size

### ISSUE THREAD

**Issue by JavierGallego** [madewithpepper/store-finder-pro#2]
Hi team!, I have a little problem with the text info on any info window on a map, the text don't display full....

where is possible change the size?,

**Comment by skokhuis** [comment]
The Google Maps infoWindow scales fine for me with more content.

**Comment by JavierGallego** [comment]
Not in my case, I attach a screenshot
![sin-titulo-1](https://cloud.githubusercontent.com/assets/13655943/12349091/2fe35046-bb6d-11e5-9679-5f3d84e7b057.png)

**Comment by skokhuis** [comment]
That's CSS related. Search for .info-container in map.css and change overflow to auto.
